

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.30.93:3306/hippo4j_manager?useUnicode=true&characterEncoding=UTF-8&?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: YF105K0MmMrRvWPv
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    map-underscore-to-camel-case: true